### PR TITLE
Replace Admin Credentials with Client Credentials Flow and Improve Token Management

### PR DESCRIPTION
**Pull request by Andreufb**
This merge request introduces several important changes that enhance security, testing, and system status checks. Key updates include:

### Summary of Changes:
1. Introspection Function: The introspection function now uses a token generated via the client credentials method, ensuring the API can perform token introspection without exposing sensitive admin information.

2. Dynamic Tokens in Tests: Replaced static tokens with dynamically generated access tokens in all tests for improved reliability and security.

3. Test Updates: Updated tests for creating, searching, and deleting resources (Kafka, URL, S3) under organizations using dynamically generated tokens.

4. Login Validation Tests: Added tests for login validation, covering both failure scenarios with incorrect credentials and successful token generation with correct credentials.

5. Status Checks for Keycloak: Updated status_routes/get.py and services/default_services/index.py to correctly check if Keycloak is up and running, ensuring accurate system status reporting.

### Impact:

- Security: No hardcoded admin credentials are used, improving the overall security of the API by switching to client credentials flow.
- Reliability: Improved the reliability of tests by using dynamically generated tokens in place of static ones.
- System Stability: Enhanced system status checks for CKAN and Keycloak, ensuring better monitoring and availability checks.

## Notes for Reviewers:
- Ensure that the new client credentials flow is functioning as expected in both introspection and status checks.
- Validate that all test updates are working correctly, particularly with the dynamic token generation and login validation scenarios.

### CODE REVIEW

**Comment by Andreufb** [comment]
Done. I have made some testing and works fine but there are lots of changes so more testing si advised

**Review by rbardaji — CHANGES_REQUESTED** [review]
The tests must remain the same as already written and cannot be modified. However, new tests can be added. The proposed changes ignore that there is a token used for testing, which doesn't need to be created from Keycloak. The variable keycloak_settings.test_token is specifically meant to bypass Keycloak authentication and allow the rest of the functions to be tested.

**Comment by Andreufb** [comment]
Changes done, please review and merge whenever is convinient.

**Review by rbardaji — COMMENTED** [review]
ok

**Pull request merged**
